### ISSUE TITLE
[BUG] Unhandled exception error since upgrading to version with device_info_plus_platform

### ISSUE THREAD

**Issue by DanMossa** [jhomlala/catcher#157]
**Describe the bug**
Running my app now produces the error 

```
E/flutter ( 8001): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
E/flutter ( 8001): #0      new List.from (dart:core-patch/array_patch.dart:40)
E/flutter ( 8001): #1      AndroidDeviceInfo._fromList (package:device_info_plus_platform_interface/model/android_device_info.dart:144)
E/flutter ( 8001): #2      AndroidDeviceInfo.fromMap (package:device_info_plus_platform_interface/model/android_device_info.dart:137)
E/flutter ( 8001): #3      MethodChannelDeviceInfo.androidInfo (package:device_info_plus_platform_interface/method_channel/method_channel_device_info.dart:19)
E/flutter ( 8001): <asynchronous suspension>
E/flutter ( 8001): #4      DeviceInfoPlugin.androidInfo (package:device_info_plus/device_info_plus.dart:65)
E/flutter ( 8001): <asynchronous suspension>
E/flutter ( 8001): #5      Catcher._loadDeviceInfo.<anonymous closure> (package:catcher/core/catcher.dart)
E/flutter ( 8001): <asynchronous suspension>
E/flutter ( 8001): 
```

The app still continues

**To Reproduce**
Run app. This is my main.dart
```
Future<void> main() async {
  final List<LocalizationOptions> _localizationOptions = [
    LocalizationOptions.buildDefaultEnglishOptions(),
    LocalizationOptions.buildDefaultSpanishOptions(),
  ];

  final CatcherOptions debugOptions = CatcherOptions(
      DialogReportMode(),
      [
        ConsoleHandler(),
      ],
      localizationOptions: _localizationOptions);
  final CatcherOptions releaseOptions = CatcherOptions(
      DialogReportMode(),
      [
        EmailManualHandler(["crashsupport@<REDACTED>.com"])
      ],
      localizationOptions: _localizationOptions);

  Catcher(
      debugConfig: debugOptions,
      releaseConfig: releaseOptions,
      runAppFunction: () async {
        runApp(
          MultiProvider(
            providers: [
              ChangeNotifierProvider(create: (_) => AppbarProvider()),
              ChangeNotifierProvider(create: (_) => UserProvider()),
              ChangeNotifierProvider(create: (_) => NavbarProvider()),
              ChangeNotifierProvider(create: (_) => MiscProvider()),
              ChangeNotifierProvider(create: (_) => GlobalProvider()),
              ChangeNotifierProvider(create: (_) => BackupProvider()),
            ],
            child: const MyApp(),
          ),
        );
      });
}

class MyApp extends StatefulWidget {
  const MyApp({
    Key? key,
  }) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: appThemeData,
      locale: Locale(context.watch<UserProvider>().currentLanguageCode()),
      localizationsDelegates: Translations.localizationsDelegates,
      supportedLocales: Translations.supportedLocales,
      navigatorKey: Catcher.navigatorKey,
      initialRoute: '/SplashView',
      routes: <String, Widget Function(BuildContext)>{
        '/SplashView': (BuildContext context) => const SplashView(),
        '/SetupAgeView': (BuildContext context) => SetupAgeView(),
      },
    );
  }
}

```

**Expected behavior**
I would like there to not be an Unhandled Exception

**Flutter doctor**
```
❯ flutter doctor   
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on Linux, locale en_US.UTF-8)                                                                                     [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.3)
[✓] VS Code (version 1.54.1)
[✓] Connected device (3 available)

• No issues found!
```

**Catcher version**
- Version: ^0.6.2

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL
 - OS: Android 11

**Comment by jhomlala** [comment]
This is device_info_plus issue: https://github.com/fluttercommunity/plus_plugins/issues/184
Anyway I've added additional error handling to device info plus code. Probably this will be fixed with next releases. Right now you need to ignore this issue for a while.
