### ISSUE TITLE
[BUG] device_info_plus: Unhandled Exception: type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by calcitem** [jhomlala/catcher#159]
**Describe the bug**
When App run, device_info_plus throws Unhandled Exception: type 'Null' is not a subtype of type 'String'

**To Reproduce**
1. Run my App
2. See error

**Expected behavior**
No exception.

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.1.0-10.0.pre, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code (version 1.54.2)
[√] Connected device (4 available)

• No issues found!
```

**Catcher version**
- Version: 0.6.3

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5
 - OS: Android 11

**Additional context**

Console output:

```
E/flutter ( 7934): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
E/flutter ( 7934): #0      new List.from (dart:core-patch/array_patch.dart:40:5)
E/flutter ( 7934): #1      AndroidDeviceInfo._fromList (package:device_info_plus_platform_interface/model/android_device_info.dart:144:12)
E/flutter ( 7934): #2      AndroidDeviceInfo.fromMap (package:device_info_plus_platform_interface/model/android_device_info.dart:137:23)
E/flutter ( 7934): #3      MethodChannelDeviceInfo.androidInfo (package:device_info_plus_platform_interface/method_channel/method_channel_device_info.dart:19:30)
E/flutter ( 7934): <asynchronous suspension>
E/flutter ( 7934): #4      DeviceInfoPlugin.androidInfo (package:device_info_plus/device_info_plus.dart:65:36)
E/flutter ( 7934): <asynchronous suspension>
```

The content of main.dart:

```c
Future<void> main() async {
  if (!(Platform.isAndroid || Platform.isIOS)) {
    runApp(MyApp());
    return;
  }

  var catcher = Catcher(rootWidget: MyApp(), ensureInitialized: true);

  String externalDirStr;
  try {
    Directory? externalDir = await getExternalStorageDirectory();
    if (externalDir != null) {
      externalDirStr = externalDir.path.toString();
    } else {
      externalDirStr = ".";
    }
  } catch (e) {
    print(e);
    externalDirStr = ".";
  }
  String path = externalDirStr + "/crash-logs.txt";
  print("ExternalStorageDirectory: " + externalDirStr);
  String recipients = "example@domain.com";

  CatcherOptions debugOptions =
      CatcherOptions(PageReportMode(showStackTrace: true), [
    ConsoleHandler(),
    FileHandler(File(path), printLogs: true),
    EmailManualHandler([recipients], printLogs: true)
  ]);

  /// Release configuration.
  /// Same as above, but once user accepts dialog,
  /// user will be prompted to send email with crash to support.
  CatcherOptions releaseOptions =
      CatcherOptions(PageReportMode(showStackTrace: true), [
    FileHandler(File(path), printLogs: true),
    EmailManualHandler([recipients], printLogs: true)
  ]);

  CatcherOptions profileOptions =
      CatcherOptions(PageReportMode(showStackTrace: true), [
    ConsoleHandler(),
    FileHandler(File(path), printLogs: true),
    EmailManualHandler([recipients], printLogs: true)
  ]);

  /// Pass root widget (MyApp) along with Catcher configuration:
  catcher.updateConfig(
    debugConfig: debugOptions,
    releaseConfig: releaseOptions,
    profileConfig: profileOptions,
  );

  SystemChrome.setPreferredOrientations(
    [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown],
  );

  if (Platform.isAndroid) {
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(statusBarColor: Colors.transparent),
    );
  }

  SystemChrome.setEnabledSystemUIOverlays([]);
}
```

**Comment by jhomlala** [comment]
Please use search feature next time: https://github.com/jhomlala/catcher/issues/157

**Comment by calcitem** [comment]
Thanks! I will fork and revert device_info_plus plugin commit and try again.

**Comment by calcitem** [comment]
This 3rd-party plugin's exception is acceptable.
