### ISSUE TITLE
[BUG] EmailManualHandler: PlatformException(not_available, no email Managers available, null, null)

### ISSUE THREAD

**Issue by calcitem** [jhomlala/catcher#160]
**Describe the bug**
When using EmailManualHandler to send email report, PlatformException occurred.

**To Reproduce**
1. Exception which is catched occurred
2. Click 'Accept'
2. See error

**Expected behavior**
No exception.

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.1.0-10.0.pre, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code (version 1.54.2)
[√] Connected device (4 available)

• No issues found!
```

**Catcher version**
- Version: 0.6.3

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5 (I try to use another Android 10 device, no error.)
 - OS: Android 11

**Additional context**

Console output:

```
I/flutter (30688): [2021-03-18 13:19:16.523126 | ConsoleHandler | INFO] ------- STACK TRACE -------
I/flutter (30688): [2021-03-18 13:19:16.523401 | ConsoleHandler | INFO] #0      _AboutPageState._launchURL (package:myapp/widgets/about_page.dart:174:7)
I/flutter (30688): [2021-03-18 13:19:16.523762 | ConsoleHandler | INFO] <asynchronous suspension>
I/flutter (30688): [2021-03-18 13:19:16.523864 | ConsoleHandler | INFO] 
I/flutter (30688): [2021-03-18 13:19:16.524360 | ConsoleHandler | INFO] ======================================================================
I/flutter (30688): [2021-03-18 13:19:16.533689 | EmailManualHandler | INFO] Creating mail request
I/flutter (30688): [2021-03-18 13:19:16.542544 | Catcher | INFO] Report result: true
E/FLUTTER_MAILER(30688): size is null or Zero
I/flutter (30688): [2021-03-18 13:19:17.177817 | EmailManualHandler | INFO] Exception occurred: PlatformException(not_available, no email Managers available, null, null) stack: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
I/flutter (30688): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
I/flutter (30688): <asynchronous suspension>
I/flutter (30688): #2      FlutterMailer.send (package:flutter_mailer/flutter_mailer.dart:16:9)
I/flutter (30688): <asynchronous suspension>
I/flutter (30688): #3      EmailManualHandler._sendEmail (package:catcher/handlers/email_manual_handler.dart:49:7)
I/flutter (30688): <asynchronous suspension>
I/flutter (30688): #4      Future.timeout.<anonymous closure> (dart:async/future_impl.dart)
I/flutter (30688): <asynchronous suspension>
I/flutter (30688): [2021-03-18 13:19:17.178148 | Catcher | INFO] Report result: false
I/flutter (30688): [2021-03-18 13:19:17.178311 | Catcher | WARNING] Instance of 'EmailManualHandler' failed to report error
```

The content of main.dart:

```c
Future<void> main() async {
  if (!(Platform.isAndroid || Platform.isIOS)) {
    runApp(MyApp());
    return;
  }

  var catcher = Catcher(rootWidget: MyApp(), ensureInitialized: true);

  String externalDirStr;
  try {
    Directory? externalDir = await getExternalStorageDirectory();
    if (externalDir != null) {
      externalDirStr = externalDir.path.toString();
    } else {
      externalDirStr = ".";
    }
  } catch (e) {
    print(e);
    externalDirStr = ".";
  }
  String path = externalDirStr + "/crash-logs.txt";
  print("ExternalStorageDirectory: " + externalDirStr);
  String recipients = "example@domain.com";

  CatcherOptions debugOptions =
      CatcherOptions(PageReportMode(showStackTrace: true), [
    ConsoleHandler(),
    FileHandler(File(path), printLogs: true),
    EmailManualHandler([recipients], printLogs: true)
  ]);

  /// Release configuration.
  /// Same as above, but once user accepts dialog,
  /// user will be prompted to send email with crash to support.
  CatcherOptions releaseOptions =
      CatcherOptions(PageReportMode(showStackTrace: true), [
    FileHandler(File(path), printLogs: true),
    EmailManualHandler([recipients], printLogs: true)
  ]);

  CatcherOptions profileOptions =
      CatcherOptions(PageReportMode(showStackTrace: true), [
    ConsoleHandler(),
    FileHandler(File(path), printLogs: true),
    EmailManualHandler([recipients], printLogs: true)
  ]);

  /// Pass root widget (MyApp) along with Catcher configuration:
  catcher.updateConfig(
    debugConfig: debugOptions,
    releaseConfig: releaseOptions,
    profileConfig: profileOptions,
  );

  SystemChrome.setPreferredOrientations(
    [DeviceOrientation.portraitUp, DeviceOrientation.portraitDown],
  );

  if (Platform.isAndroid) {
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(statusBarColor: Colors.transparent),
    );
  }

  SystemChrome.setEnabledSystemUIOverlays([]);
}
```

**Comment by jhomlala** [comment]
Seems like you don't have any email app (email manager) available in your device. Can you setup some and try again?

**Comment by calcitem** [comment]
I installed Outlook. The gmail is pre-installed.

**Comment by calcitem** [comment]
Android simulator also has this exception. I will file a case to the Author of mailer.

**Comment by calcitem** [comment]
Solution: https://github.com/taljacobson/flutter_mailer/issues/38
