### ISSUE TITLE
Sentry: i do not see stackTrace in Sentry (maybe it does not passed?)

### ISSUE THREAD

**Issue by ValeriusGC** [jhomlala/catcher#191]
Hi! In console i see it:
```
I/flutter ( 7949): [2021-07-23 11:12:51.803615 | Catcher | INFO] ---------- ERROR ----------
I/flutter ( 7949): [2021-07-23 11:12:51.803699 | Catcher | INFO] "AuthService" not found. You need to call "Get.put(AuthService())" or "Get.lazyPut(()=>AuthService())"
I/flutter ( 7949): [2021-07-23 11:12:51.803790 | Catcher | INFO] 
I/flutter ( 7949): [2021-07-23 11:12:51.804076 | Catcher | INFO] ------- STACK TRACE -------
I/flutter ( 7949): [2021-07-23 11:12:51.804283 | Catcher | INFO] #0      GetInstance.find (package:get/get_instance/src/get_instance.dart:357:7)
I/flutter ( 7949): [2021-07-23 11:12:51.804364 | Catcher | INFO] #1      Inst.find (package:get/get_instance/src/extension_instance.dart:70:45)
I/flutter ( 7949): [2021-07-23 11:12:51.804430 | Catcher | INFO] #2      new DataService (package:torex/shared/services/data_service.dart:37:43)
I/flutter ( 7949): [2021-07-23 11:12:51.804499 | Catcher | INFO] #3      initServices.<anonymous closure> (package:torex/shared/services/services.dart:31:21)
I/flutter ( 7949): [2021-07-23 11:12:51.804583 | Catcher | INFO] #4      _InstanceBuilderFactory.getDependency (package:get/get_instance/src/get_instance.dart:567:33)
I/flutter ( 7949): [2021-07-23 11:12:51.804670 | Catcher | INFO] #5      GetInstance._startController (package:get/get_instance/src/get_instance.dart:307:28)
I/flutter ( 7949): [2021-07-23 11:12:51.804747 | Catcher | INFO] #6      GetInstance._initDependencies (package:get/get_instance/src/get_instance.dart:264:11)
I/flutter ( 7949): [2021-07-23 11:12:51.804815 | Catcher | INFO] #7      GetInstance.find (package:get/get_instance/src/get_instance.dart:353:17)
I/flutter ( 7949): [2021-07-23 11:12:51.804877 | Catcher | INFO] #8      Inst.find (package:get/get_instance/src/extension_instance.dart:70:45)
I/flutter ( 7949): [2021-07-23 11:12:51.804949 | Catcher | INFO] #9      new InvestService (package:torex/shared/services/invest_service.dart:16:43)
I/flutter ( 7949): [2021-07-23 11:12:51.805014 | Catcher | INFO] #10     initServices (package:torex/shared/services/services.dart:46:33)
I/flutter ( 7949): [2021-07-23 11:12:51.805084 | Catcher | INFO] <asynchronous suspension>

```
But in Sentry i see only short info like that (see picture):
![Screenshot from 2021-07-23 11-22-29](https://user-images.githubusercontent.com/3320861/126744486-ad759cb0-f2b1-4f09-b6ad-57260b4d1907.png)

**Comment by jhomlala** [comment]
I can see normal stack trace in Sentry. Maybe you're checking wrong section in the Sentry? I assume Sentry receives whole stack trace and it should handle in normally. Please check "Issues" tab in Sentry. You can also contact Sentry team here (Catcher uses Sentry plugin): https://github.com/getsentry/sentry-dart
