### ISSUE TITLE
[BUG]Can't catch IsolateError

### ISSUE THREAD

**Issue by JaminZhou** [jhomlala/catcher#196]
**Describe the bug**
Can't catch IsolateError

**To Reproduce**
change the generateError impl
```dart
class ChildWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: TextButton(
        child: Text("Generate error"),
        onPressed: () => generateError(),
      ),
    );
  }
}

void generateError() {
  Isolate.spawn(entryPoint, "message");
}

void entryPoint(String message){
  throw StateError('Errors');
}
```

the error info in the console
```batch
[VERBOSE-2:dart_isolate.cc(1137)] Unhandled exception:
Bad state: Errors
#0      entryPoint
package:catcher_example/main.dart:95
#1      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:286:17)
#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9011374/135761747-2e137ed5-1ceb-47db-af9d-ca435fbdbee2.png)

**Flutter doctor**
Please add flutter doctor output here.

**Catcher version**
- Version: 0.6.8

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone13 Simulator]
 - OS: [e.g. iOS15]

**Additional context**

**Comment by JaminZhou** [comment]
Exceptions and errors in isolates other than the main isolate can't be caught automatically.
