### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hiperioncn** [jhomlala/catcher#271]
**Describe the bug**
I used the sample code 
[https://github.com/jhomlala/catcher/blob/master/example/lib/update_config_example.dart](https://github.com/jhomlala/catcher/blob/master/example/lib/update_config_example.dart )
to modify the config. I found that it was normal before modifying the config. After modifying the config file, the console Printing is repeated. Something like this:

`============================ CATCHER LOG ============================
============================ CATCHER LOG ============================
Crash occurred on 2024-04-15 16:55:24.421906
Crash occurred on 2024-04-15 16:55:24.421906
------- DEVICE INFO -------
------- DEVICE INFO -------
id: UP1A.231005.007
id: UP1A.231005.007
board: lahaina
board: lahaina
bootloader: G9910ZCS6FXA1
bootloader: G9910ZCS6FXA1
brand: samsung
brand: samsung
device: o1q
device: o1q
display: UP1A.231005.007.G9910ZCSXA1
display: UP1A.231005.007.G9910ZCSXA1
fingerprint: samsung/o1qzcx/o1q:14/UP1A.231005.007/G991S6FXA1:user/release-keys
fingerprint: samsung/o1qzcx/o1q:14/UP1A.231005.007/G991S6FXA1:user/release-keys
hardware: qcom
hardware: qcom
host: 21DKGA14
host: 21DKGA14
isPhysicalDevice: true
isPhysicalDevice: true
manufacturer: samsung
manufacturer: samsung
model: SM-G9910
model: SM-G9910
product: o1qzcx
product: o1qzcx
tags: release-keys
tags: release-keys
type: user
type: user
versionBaseOs: samsung/o1qzcx/o1q:14/UP1A.231005.007/G99106FWL2:user/release-keys
versionBaseOs: samsung/o1qzcx/o1q:14/UP1A.231005.007/G99106FWL2:user/release-keys
versionCodename: REL
versionCodename: REL
versionIncremental: G9910ZFXA1
versionIncremental: G9910ZFXA1
versionPreviewSdk: 0
versionPreviewSdk: 0
versionRelease: 14
versionRelease: 14
versionSdk: 34
versionSdk: 34
versionSecurityPatch: 2023-12-01
versionSecurityPatch: 2023-12-01
------- APP INFO -------
------- APP INFO -------
environment: debug
environment: debug
version: 1.0.0
version: 1.0.0
appName: xxx
appName: xxx
buildNumber: 3
buildNumber: 3
packageName: com.xxx.xxx
packageName: com.xxx.xxx
---------- ERROR ----------
---------- ERROR ----------
FormatException: Test exception generated by Catcher
FormatException: Test exception generated by Catcher
------- STACK TRACE -------
------- STACK TRACE -------
#0      Catcher.sendTestException (package:catcher/core/catcher.dart:716:5)
#0      Catcher.sendTestException (package:catcher/core/catcher.dart:716:5)
#1      ChildWidget.generateError (package:unifi_platform/main.dart:76:13)
#1      ChildWidget.generateError (package:unifi_platform/main.dart:76:13)
#2      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
#2      _InkResponseState.handleTap (package:flutter/src/material/ink_well.dart:1183:21)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:315:24)
#3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:315:24)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:652:11)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:309:5)
#6      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#6      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:242:7)
#7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:670:9)
#7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:670:9)
#8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_r
#9      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_r
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#11     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#11     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430:11)
#15     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:430:11)
#16     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#16     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#17     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#17     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#20     _rootRunUnary (dart:async/zone.dart:1415:13)
#20     _rootRunUnary (dart:async/zone.dart:1415:13)
#21     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#21     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#23     _invoke1 (dart:ui/hooks.dart:330:10)
#23     _invoke1 (dart:ui/hooks.dart:330:10)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
#24     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:429:7)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
#25     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
======================================================================
======================================================================
Report result: true
Report result: true`

**To Reproduce**
click "Change Config"
click "Generate error"
Got Repeated log

**Flutter doctor**
[✓] Flutter (Channel stable, 3.19.3, on macOS 14.4.1 23E224 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.88.0)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!

**Catcher version**
- Version: 0.8.0

**Smartphone (please complete the following information):**
 - Device: Samsung S21
 - OS: Android14 OneUI6.0

**Comment by yecaiyu1999** [comment]
me too
