### ISSUE TITLE
Not working on my app

### ISSUE THREAD

**Issue by rignaneseleo** [jhomlala/catcher#85]
Hi, great job!
I'd like to have this on my app but sadly I tried to add it but it doesn't work: it doesn't catches errors and handles them. 

With the following main:
```
Future main() async {
  WidgetsFlutterBinding.ensureInitialized();
  SharedPreferences sp = await SharedPreferences.getInstance();
  FirebaseAnalytics analytics = FirebaseAnalytics();
  globals.packageInfo = await PackageInfo.fromPlatform();

  CatcherOptions debugOptions = CatcherOptions(SilentReportMode(), [
    ConsoleHandler(),
  ]);
  Catcher(
      MaterialApp(
        navigatorKey: Catcher.navigatorKey,
        title: "app",
        theme: MgkTheme,
        initialRoute: '/',
        debugShowCheckedModeBanner: !kReleaseMode,
        routes: {
          '/': (context) => new SplashScreenPage(),
          '/home': (context) => new HomePage(key: globals.homePageKey),
          '/members': (context) => new HomePage(initPage: 1),
          '/blacklist': (context) => new BlackListPage(),
          '/notifications': (context) => new NotificationsPage(),
          '/friendinvites': (context) => new FriendsEchoPage(),
          '/familys': (context) => new FamilyTreePage(),
          '/debug': (context) => new DebugPage(),
          '/selector': (context) => new FamilySelectorPage(),
          '/settings': (context) => new SettingsPage(),
          '/help': (context) => new HelpPage(),
        },
        supportedLocales: [Locale('en', 'US'), Locale('it', 'IT')],
        localizationsDelegates: [
          // A class which loads the translations from JSON files
          AppLocalizations.delegate,
          // Built-in localization of basic text for Material widgets
          GlobalMaterialLocalizations.delegate,
          // Built-in localization for text direction LTR/RTL
          GlobalWidgetsLocalizations.delegate,
        ],
        localeResolutionCallback: (locale, supportedLocales) {
          if (locale == null) return supportedLocales.first;

          // Check if the current device locale is supported
          for (var supportedLocale in supportedLocales) {
            if (supportedLocale.languageCode == locale.languageCode &&
                supportedLocale.countryCode == locale.countryCode) {
              return supportedLocale;
            }
          }
          // If the locale of the device is not supported, use the first one
          // from the list (English, in this case).
          return supportedLocales.first;
        },
        navigatorObservers: [
          if (sp.getBool("sendDataUsage") ?? false)
            FirebaseAnalyticsObserver(analytics: analytics),
        ],
      ),
      enableLogger: true,
      debugConfig: debugOptions);
}
```

and using the following button in DebugPage:
```
 MaterialButton(
              child: Text("Simulate crash"),
              onPressed: () async {
                Catcher.sendTestException();
              },
),
```

I get nothing more than a normal exception in my console:

```
E/flutter (32579): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Test exception generated by Catcher
E/flutter (32579): #0      Catcher.sendTestException (package:catcher/core/catcher.dart:398:5)
E/flutter (32579): #1      _DebugPageState.build.<anonymous closure> (package:my_grand_kids/screens/debug_page.dart:59:25)
E/flutter (32579): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:779:14)
E/flutter (32579): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:862:36)
E/flutter (32579): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (32579): #5      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (32579): #6      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (32579): #7      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter (32579): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (32579): #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (32579): #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (32579): #11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (32579): #12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (32579): #13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (32579): #14     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (32579): #15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (32579): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (32579): #17     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (32579): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
```

What am I doing wrong?

My flutter doctor: 

```
[✓] Flutter (Channel dev, v1.15.20, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.15.20 at /Users/leo/Dev/flutter
    • Framework revision 4049889d9e (6 weeks ago), 2020-03-10 20:05:41 -0700
    • Engine revision 0e2c8feeeb
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/leo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • ONEPLUS A5010 • 67488e7a • android-arm64 • Android 9 (API 28)

• No issues found!
```

PS: I suggest you to make the setup instruction clearer: write down a bullet list of the items we need to add on our project in order to make it work. Simple and easy.

**Comment by jhomlala** [comment]
You're doing everything Ok, but Flutter in debug mode catches too much. Check this topic: 
https://github.com/jhomlala/catcher/issues/75

Thanks for your suggestion.
